### ISSUE TITLE
Reaction network DSL doesn't properly handle the order of reactions

### ISSUE THREAD

**Issue by saolof** [JuliaDiffEq/DiffEqBiological.jl#16] opened 2018-02-10 23:58 UTC
I noticed that currently, the reaction networks DSL only takes stoichiometry into account. So it treats A -> 0 and A + A -> A  as the same system.

However, because of the law of mass action, the former is just exponential decay  (a decay rate proportional to the concentration) with a solution of the form [A_0] e^-kt  , while the second is a rational decay (the decay rate is proportional to the concentration squared) with a solution of the form 1 /  (k t + [A_0]^-1 ) where k is the reaction rate and A_0 the initial concentration.

The two behave rather differently even from a qualitative point of view. In a system of equations, A would stick around and influence the system for much longer in the second case. If we add a second row A + B -> A at a much smaller rate than the decay rate of A, then in the first case the concentration of B will be negligibly affected, while in the second case it will be significantly affected as the integral of A over time diverges.

**Comment by ChrisRackauckas** [comment] 2018-02-11 05:00
Duplicate of https://github.com/JuliaDiffEq/DiffEqBiological.jl/issues/10 and hopefully being handled by https://github.com/JuliaDiffEq/DiffEqBiological.jl/pull/15. Please check out #15 and help us handle it correctly 👍

**Closed by ChrisRackauckas** 2018-02-11 05:00 UTC

**Comment by saolof** [comment] 2018-02-11 19:32
Ah right, #15 is very recent and I had missed it. Looking through it, it's very well thought out and looks like something I could get quite a lot of use out of in the coming months.
